### ISSUE TITLE
test2

### ISSUE THREAD

**Issue by thesuperzapper** [thesuperzapper/charts#2]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

<img src="https://img.shields.io/static/v1?style=for-the-badge&label=&message=Tip&color=blue">

### Kubernetes Version

```shell
Client Version: version.Info{Major:"X", Minor:"XX", GitVersion:"vX.X.X", ...}
Server Version: version.Info{Major:"X", Minor:"XX", GitVersion:"vX.X.X", ...}
```

### Helm Version

```shell
version.BuildInfo{Version:"vX.X.X", GitCommit:"XXXXXXXXXXXXXXX", ...}
```

### Description

I was trying to... but then...

### Relevant Logs

```shell
1
2
3
4
4
5
```

### Custom Helm Values

```yaml
###################################
## CONFIG | Airflow Configs
###################################
airflow:
  image:
    ...
  config:
    ...

###################################
## COMPONENT | Airflow Scheduler
###################################
scheduler:
  ...
```
